In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
type(a)

numpy.ndarray

In [5]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [6]:
#Creating 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [7]:
#Creaating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
print(a3)
type(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


numpy.ndarray

In [8]:
print(a2.shape)
print(a3.shape)

(2, 3)
(3, 2, 3)


In [9]:
print(a2.ndim)
print(a3.ndim)

2
3


In [10]:
print(a2.dtype)

int32


In [11]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.random.randint(1,11, size=(2,3))

array([[4, 3, 5],
       [3, 5, 8]])

In [15]:
np.random.randint(1,11, size=(3,2,3))

array([[[ 5,  1,  6],
        [ 4,  4,  6]],

       [[ 6,  6,  4],
        [ 2,  9,  3]],

       [[ 9, 10, 10],
        [ 7,  6, 10]]])

In [16]:
x = np.random.randint(1,21, size=(2,2))
y = np.random.randint(1,21, size=(2,2))
print(x)
print(y)


[[ 4  8]
 [ 5 18]]
[[ 9  8]
 [11  4]]


In [17]:
print(x+y)
print(x-y)
print(x*y)

[[13 16]
 [16 22]]
[[-5  0]
 [-6 14]]
[[36 64]
 [55 72]]


In [18]:
#matrix multiplication
#1st method
print(x @ y)

[[124  64]
 [243 112]]


In [19]:
#2nd method
np.dot(x,y)

array([[124,  64],
       [243, 112]])

In [20]:
x.prod()

2880

In [21]:
x.mean()
y.mean()

8.0

In [22]:
print(x)

[[ 4  8]
 [ 5 18]]


In [23]:
b = x.mean(axis=0) #column wise
print(b)

[ 4.5 13. ]


In [24]:
c = x.mean(axis=1) #row wise
print(c)

[ 6.  11.5]


In [25]:
print(x.sum())
print(x.std())
print(x.var())

35
5.539629951540085
30.6875


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr, 50))
print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

5.0
3.0
7.0


In [27]:
arr2 = np.random.randint(11,100, (4,4))
print(arr2)

[[41 24 64 62]
 [59 18 26 83]
 [49 53 82 50]
 [17 85 20 93]]


In [28]:
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[41 24 64 62 59 18 26 83]
 [49 53 82 50 17 85 20 93]]
8x2
[[41 24]
 [64 62]
 [59 18]
 [26 83]
 [49 53]
 [82 50]
 [17 85]
 [20 93]]


In [29]:
print(arr2)

[[41 24 64 62]
 [59 18 26 83]
 [49 53 82 50]
 [17 85 20 93]]


In [36]:
print(arr2[0]) #0th row
print(arr2[0,1]) #0th row 1st column
print(arr2[-1]) #last row
print(arr2[:3]) #0th to 2nd row
print(arr2[1:]) #1st to last row

[41 24 64 62]
24
[17 85 20 93]
[[41 24 64 62]
 [59 18 26 83]
 [49 53 82 50]]
[[59 18 26 83]
 [49 53 82 50]
 [17 85 20 93]]


In [37]:
arr2 > 50

array([[False, False,  True,  True],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [False,  True, False,  True]])

In [44]:
y = arr2[arr2>50]
z = y.reshape(4,2)
print(z)

[[64 62]
 [59 83]
 [53 82]
 [85 93]]
